import type { Variante } from './tokens'

const display = "'Geist Sans', system-ui, sans-serif"
const body = "'Geist Sans', system-ui, sans-serif"

export const calidoVariantes: Variante[] = [
  {
    familia: 'calido-y-amigable',
    paleta: 'melocoton',
    label: 'Melocotón + rosa suave + terracota',
    descripcion: 'Calidez de hogar. Tonos durazno y terracota que invitan a quedarse.',
    tokens: {
      '--bg': '#fef6f0',
      '--bg-alt': '#fbe8d8',
      '--fg': '#3a2820',
      '--fg-muted': '#86695b',
      '--primary': '#d96b3a',
      '--primary-fg': '#ffffff',
      '--accent': '#f4a577',
      '--accent-fg': '#3a2820',
      '--border': '#f0d9c4',
      '--card': '#ffffff',
      '--card-fg': '#3a2820',
      '--radius': '20px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'calido-y-amigable',
    paleta: 'crema',
    label: 'Crema + verde salvia + marrón',
    descripcion: 'Salvia tranquilo, crema acogedor. Una clínica que se siente como un café favorito.',
    tokens: {
      '--bg': '#faf6ee',
      '--bg-alt': '#f0ead8',
      '--fg': '#2e2820',
      '--fg-muted': '#766b58',
      '--primary': '#6b8463',
      '--primary-fg': '#ffffff',
      '--accent': '#a47d5a',
      '--accent-fg': '#ffffff',
      '--border': '#e3dcc4',
      '--card': '#ffffff',
      '--card-fg': '#2e2820',
      '--radius': '20px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'calido-y-amigable',
    paleta: 'lavanda',
    label: 'Lavanda + rosa pálido + lila',
    descripcion: 'Frescura floral. Pétalos de lavanda y rosa para una experiencia serena.',
    tokens: {
      '--bg': '#faf7fc',
      '--bg-alt': '#f0e8f5',
      '--fg': '#2e2438',
      '--fg-muted': '#7a6a86',
      '--primary': '#8463a8',
      '--primary-fg': '#ffffff',
      '--accent': '#d49bbe',
      '--accent-fg': '#2e2438',
      '--border': '#e6dbed',
      '--card': '#ffffff',
      '--card-fg': '#2e2438',
      '--radius': '20px',
      '--font-body': body,
      '--font-display': display,
    },
  },
]
