import type { Variante } from './tokens'

const display = "'Geist Sans', system-ui, sans-serif"
const body = "'Geist Sans', system-ui, sans-serif"

export const clinicoVariantes: Variante[] = [
  {
    familia: 'clinico-y-profesional',
    paleta: 'azul-medico',
    label: 'Azul médico + blanco + gris',
    descripcion: 'El azul de la confianza médica. Limpieza absoluta, autoridad clínica.',
    tokens: {
      '--bg': '#ffffff',
      '--bg-alt': '#f1f5f9',
      '--fg': '#0f172a',
      '--fg-muted': '#64748b',
      '--primary': '#1d6fbb',
      '--primary-fg': '#ffffff',
      '--accent': '#0ea5e9',
      '--accent-fg': '#ffffff',
      '--border': '#e2e8f0',
      '--card': '#ffffff',
      '--card-fg': '#0f172a',
      '--radius': '8px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'clinico-y-profesional',
    paleta: 'teal',
    label: 'Teal + blanco + gris oscuro',
    descripcion: 'Verde azulado moderno. Una clínica tech-forward con identidad propia.',
    tokens: {
      '--bg': '#ffffff',
      '--bg-alt': '#f0fafa',
      '--fg': '#1a2b2b',
      '--fg-muted': '#5f7373',
      '--primary': '#0f7a73',
      '--primary-fg': '#ffffff',
      '--accent': '#14b8a6',
      '--accent-fg': '#ffffff',
      '--border': '#d8e6e5',
      '--card': '#ffffff',
      '--card-fg': '#1a2b2b',
      '--radius': '8px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'clinico-y-profesional',
    paleta: 'azul-cielo',
    label: 'Azul cielo + verde menta + blanco',
    descripcion: 'Suavidad pediátrica sin sacrificar profesionalismo. Acogedor para todas las edades.',
    tokens: {
      '--bg': '#ffffff',
      '--bg-alt': '#eff8fc',
      '--fg': '#1a2937',
      '--fg-muted': '#5c6e80',
      '--primary': '#3b9bc4',
      '--primary-fg': '#ffffff',
      '--accent': '#5fc9a3',
      '--accent-fg': '#0f2a1f',
      '--border': '#d6e6ee',
      '--card': '#ffffff',
      '--card-fg': '#1a2937',
      '--radius': '12px',
      '--font-body': body,
      '--font-display': display,
    },
  },
]
