import type { Variante } from './tokens'

const display = "'Playfair Display', Georgia, serif"
const body = "'Geist Sans', system-ui, sans-serif"

export const eleganteVariantes: Variante[] = [
  {
    familia: 'elegante-y-sofisticado',
    paleta: 'gris',
    label: 'Gris perla + rosa antiguo + dorado',
    descripcion: 'Sutileza y refinamiento. Un susurro de oro sobre un lienzo de perla.',
    tokens: {
      '--bg': '#f5f3f0',
      '--bg-alt': '#ebe7e1',
      '--fg': '#2a2724',
      '--fg-muted': '#6b655e',
      '--primary': '#9c6b58',
      '--primary-fg': '#fdfcfb',
      '--accent': '#c9a96e',
      '--accent-fg': '#2a2724',
      '--border': '#d8d3cc',
      '--card': '#ffffff',
      '--card-fg': '#2a2724',
      '--radius': '2px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'elegante-y-sofisticado',
    paleta: 'azul',
    label: 'Azul acero + blanco + bronce',
    descripcion: 'Frialdad serena del acero, calidez del bronce. Sofisticación contemporánea.',
    tokens: {
      '--bg': '#f8f9fb',
      '--bg-alt': '#eaeef3',
      '--fg': '#1a232e',
      '--fg-muted': '#5a6675',
      '--primary': '#3f5973',
      '--primary-fg': '#ffffff',
      '--accent': '#a87c4f',
      '--accent-fg': '#ffffff',
      '--border': '#d1d8e0',
      '--card': '#ffffff',
      '--card-fg': '#1a232e',
      '--radius': '2px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'elegante-y-sofisticado',
    paleta: 'nude',
    label: 'Nude + grafito + oro rosa',
    descripcion: 'Pieles cálidas y grafito profundo, con destellos de oro rosa. Femenino y atemporal.',
    tokens: {
      '--bg': '#f7f1ec',
      '--bg-alt': '#ede3da',
      '--fg': '#2c2723',
      '--fg-muted': '#6e635a',
      '--primary': '#3a3531',
      '--primary-fg': '#f7f1ec',
      '--accent': '#c98a72',
      '--accent-fg': '#ffffff',
      '--border': '#dbd0c4',
      '--card': '#ffffff',
      '--card-fg': '#2c2723',
      '--radius': '2px',
      '--font-body': body,
      '--font-display': display,
    },
  },
  {
    familia: 'elegante-y-sofisticado',
    paleta: 'video',
    label: 'Gris perla + video hero',
    descripcion: 'La misma elegancia editorial con un hero cinematográfico de fondo.',
    video: '/videos/elegante.mp4',
    tokens: {
      '--bg': '#f5f3f0',
      '--bg-alt': '#ebe7e1',
      '--fg': '#2a2724',
      '--fg-muted': '#6b655e',
      '--primary': '#9c6b58',
      '--primary-fg': '#fdfcfb',
      '--accent': '#c9a96e',
      '--accent-fg': '#2a2724',
      '--border': '#d8d3cc',
      '--card': '#ffffff',
      '--card-fg': '#2a2724',
      '--radius': '2px',
      '--font-body': body,
      '--font-display': display,
    },
  },
]
