import type { Variante } from './tokens'

const display = "'Cormorant Garamond', Georgia, serif"
const body = "'Geist Sans', system-ui, sans-serif"

export const lujosoVariantes: Variante[] = [
  {
    familia: 'lujoso-y-premium',
    paleta: 'negro',
    label: 'Negro + dorado + crema',
    descripcion: 'El estándar de oro del lujo. Negro profundo, oro real, crema cálida.',
    tokens: {
      '--bg': '#0c0b0a',
      '--bg-alt': '#181614',
      '--fg': '#f5ede0',
      '--fg-muted': '#a89c87',
      '--primary': '#d4af37',
      '--primary-fg': '#0c0b0a',
      '--accent': '#e8d8b8',
      '--accent-fg': '#0c0b0a',
      '--border': '#2c2823',
      '--card': '#161412',
      '--card-fg': '#f5ede0',
      '--radius': '0px',
      '--font-body': body,
      '--font-display': display,
      '--scrollbar-thumb': '#d4af37',
      '--scrollbar-thumb-hover': '#e8c94a',
    },
  },
  {
    familia: 'lujoso-y-premium',
    paleta: 'azul-marino',
    label: 'Azul marino + cobre + blanco',
    descripcion: 'Profundidades del océano y el brillo del cobre. Náutico, elevado, atemporal.',
    tokens: {
      '--bg': '#0a1424',
      '--bg-alt': '#101e35',
      '--fg': '#f4f1ec',
      '--fg-muted': '#9aa8bf',
      '--primary': '#c97f4d',
      '--primary-fg': '#0a1424',
      '--accent': '#e8b888',
      '--accent-fg': '#0a1424',
      '--border': '#1c2c45',
      '--card': '#0f1a2d',
      '--card-fg': '#f4f1ec',
      '--radius': '0px',
      '--font-body': body,
      '--font-display': display,
      '--scrollbar-thumb': '#c97f4d',
      '--scrollbar-thumb-hover': '#e0965e',
    },
  },
  {
    familia: 'lujoso-y-premium',
    paleta: 'esmeralda',
    label: 'Esmeralda + dorado + negro',
    descripcion: 'Joya verde profundo. Una clínica que se siente como una bóveda de Cartier.',
    tokens: {
      '--bg': '#08120e',
      '--bg-alt': '#0e1c16',
      '--fg': '#f3ecdc',
      '--fg-muted': '#8a9c92',
      '--primary': '#1f5d44',
      '--primary-fg': '#f3ecdc',
      '--accent': '#d4af37',
      '--accent-fg': '#08120e',
      '--border': '#1a2820',
      '--card': '#0d1a13',
      '--card-fg': '#f3ecdc',
      '--radius': '0px',
      '--font-body': body,
      '--font-display': display,
      '--scrollbar-thumb': '#1f5d44',
      '--scrollbar-thumb-hover': '#2a7a5a',
    },
  },
  {
    familia: 'lujoso-y-premium',
    paleta: 'video',
    label: 'Negro + dorado + video hero',
    descripcion: 'Drama cinematográfico: video sobre negro profundo con acentos dorados.',
    video: '/videos/lujoso.mp4',
    tokens: {
      '--bg': '#0c0b0a',
      '--bg-alt': '#181614',
      '--fg': '#f5ede0',
      '--fg-muted': '#a89c87',
      '--primary': '#d4af37',
      '--primary-fg': '#0c0b0a',
      '--accent': '#e8d8b8',
      '--accent-fg': '#0c0b0a',
      '--border': '#2c2823',
      '--card': '#161412',
      '--card-fg': '#f5ede0',
      '--radius': '0px',
      '--font-body': body,
      '--font-display': display,
      '--scrollbar-thumb': '#d4af37',
      '--scrollbar-thumb-hover': '#e8c94a',
    },
  },
]
