/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliaPaletaRouteImport } from './routes/$familia.$paleta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaPaletaRoute = FamiliaPaletaRouteImport.update({
  id: '/$familia/$paleta',
  path: '/$familia/$paleta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$familia/$paleta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$familia/$paleta'
  id: '__root__' | '/' | '/$familia/$paleta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliaPaletaRoute: typeof FamiliaPaletaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$familia/$paleta': {
      id: '/$familia/$paleta'
      path: '/$familia/$paleta'
      fullPath: '/$familia/$paleta'
      preLoaderRoute: typeof FamiliaPaletaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliaPaletaRoute: FamiliaPaletaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
